global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'booking-service'
    static_configs:
      - targets: ['booking-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'messaging-service'
    static_configs:
      - targets: ['messaging-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:80']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    scrape_timeout: 10s