apiVersion: v1
kind: Namespace
metadata:
  name: zenith-production
  labels:
    name: zenith-production
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: zenith-staging
  labels:
    name: zenith-staging
    environment: staging
